name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              gradle-${{ runner.os }}-

      - name: Cache Gradle build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-buildcache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            gradle-buildcache-${{ runner.os }}-

      - name: Gradle Build (for caching)
        run: ./gradlew build -x test --no-daemon

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Check Dependency Changes
        id: check_changes
        run: |
          git fetch origin ${{ github.event.before }}
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'build.gradle|settings.gradle|gradle.properties'; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image (with or without Cache Export)
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          if [ "${{ env.changed }}" = "true" ]; then
            echo "Dependencies changed. Exporting cache..."
            docker buildx build \
              --cache-from=type=registry,ref=yongjun0511/clokey-docker:buildcache \
              --cache-to=type=registry,ref=yongjun0511/clokey-docker:buildcache,mode=max \
              --tag yongjun0511/clokey-docker:1.0.0 \
              --push \
              .
          else
            echo "No dependency changes. Skipping cache export..."
            docker buildx build \
              --cache-from=type=registry,ref=yongjun0511/clokey-docker:buildcache \
              --tag yongjun0511/clokey-docker:1.0.0 \
              --push \
              .
          fi

      - name: Create application-secret.yml from Secret
        run: |
          mkdir -p ./temp_secret
          echo "${{ secrets.APPLICATION_SECRET }}" > ./temp_secret/application-secret.yml
        shell: bash

      - name: Copy application-secret.yml to /home/ubuntu/secret
        uses: appleboy/scp-action@v0.1.3
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./temp_secret/application-secret.yml
          target: /home/ubuntu/secret/


      - name: Copy docker-compose file to remote
        uses: appleboy/scp-action@v0.1.3
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "/home/ubuntu/cicd/"

      - name: Deploy Blue-Green
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker pull yongjun0511/clokey-docker:1.0.0 
            sudo chmod +x /home/ubuntu/cicd/deploy.sh
            sudo /home/ubuntu/cicd/deploy.sh

